function openYouTubeTranscript() {
  const allElements = document.getElementsByTagName('*');
  
  for (let i = 0; i < allElements.length; i++) {
    const el = allElements[i];
    if (el.textContent && el.textContent.toLowerCase().includes('show transcript')) {
      if (el.tagName === 'BUTTON' || el.getAttribute('role') === 'button' || 
          el.classList.contains('yt-spec-button-shape-next')) {
        el.click();
        return true;
      } else {
        const parentButton = el.closest('button, [role=\"button\"]');
        if (parentButton) {
          parentButton.click();
          return true;
        }
      }
    }
  }
  
  return false;
}

function selectAutoGeneratedTranscript() {
  const dropdownButton = document.querySelector('#menu > yt-sort-filter-sub-menu-renderer > yt-dropdown-menu > tp-yt-paper-menu-button > div > tp-yt-paper-button');
  
  if (dropdownButton) {
    dropdownButton.click();

    setTimeout(() => {
      const allItems = document.querySelectorAll('tp-yt-paper-item');
      for (let i = 0; i < allItems.length; i++) {
        const item = allItems[i];
        if (item.textContent && item.textContent.toLowerCase().includes('auto-generated')) {
          item.click();
          return;
        }
      }
    }, 500);
  }
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', function() {
    setTimeout(function() {
      if (openYouTubeTranscript()) {
        setTimeout(selectAutoGeneratedTranscript, 1000);
      }
    }, 2000);
  });
} else {
  setTimeout(function() {
    if (openYouTubeTranscript()) {
      setTimeout(selectAutoGeneratedTranscript, 1000);
    }
  }, 2000);
}
