let storedEnglishTranscript = [];

function openYouTubeTranscript() {
  const allElements = document.getElementsByTagName('*');
  
  for (let i = 0; i < allElements.length; i++) {
    const el = allElements[i];
    if (el.textContent && el.textContent.toLowerCase().includes('show transcript')) {
      if (el.tagName === 'BUTTON' || el.getAttribute('role') === 'button' || 
          el.classList.contains('yt-spec-button-shape-next')) {
        el.click();
        return true;
      } else {
        const parentButton = el.closest('button, [role=\"button\"]');
        if (parentButton) {
          parentButton.click();
          return true;
        }
      }
    }
  }
  
  return false;
}

function selectTranscriptAndStore(lang) {
  const dropdownButton = document.querySelector('#menu > yt-sort-filter-sub-menu-renderer > yt-dropdown-menu > tp-yt-paper-menu-button > div > tp-yt-paper-button');
  
  if (dropdownButton) {
    dropdownButton.click();

    setTimeout(() => {
      const allItems = document.querySelectorAll('tp-yt-paper-item');
      for (let i = 0; i < allItems.length; i++) {
        const item = allItems[i];
        if (item.textContent && item.textContent.toLowerCase().includes(lang)) {
          item.click();
          waitForTranscriptLoad(storeTranscript);
          return;
        }
      }
    }, 500);
  }
}

function waitForTranscriptLoad(callback) {
  const check = setInterval(() => {
    const transcriptLines = document.querySelectorAll('ytd-transcript-segment-renderer');
    if (transcriptLines.length > 0) {
      clearInterval(check);
      callback();
    }
  }, 100);
}

function storeTranscript() {
  const transcriptLines = document.querySelectorAll('ytd-transcript-segment-renderer');
  storedEnglishTranscript = [];

  transcriptLines.forEach(line => {
    const originalTextElement = line.querySelector('.segment-text');
    if (originalTextElement) {
      storedEnglishTranscript.push(originalTextElement.textContent.trim());
    }
  });

  selectAutoGeneratedTranscript();
}

function selectAutoGeneratedTranscript() {
  const dropdownButton = document.querySelector('#menu > yt-sort-filter-sub-menu-renderer > yt-dropdown-menu > tp-yt-paper-menu-button > div > tp-yt-paper-button');
  
  if (dropdownButton) {
    dropdownButton.click();

    setTimeout(() => {
      const allItems = document.querySelectorAll('tp-yt-paper-item');
      for (let i = 0; i < allItems.length; i++) {
        const item = allItems[i];
        if (item.textContent && item.textContent.toLowerCase().includes('auto-generated')) {
          item.click();
          waitForTranscriptLoad(injectStoredText);
          return;
        }
      }
    }, 500);
  }
}

function injectStoredText() {
  const transcriptLines = document.querySelectorAll('ytd-transcript-segment-renderer');
  
  transcriptLines.forEach((line, index) => {
    if (storedEnglishTranscript[index]) {
      const newDiv = document.createElement('div');
      newDiv.className = 'translated-text';
      newDiv.style.color = '#717171';
      newDiv.style.marginTop = '4px';
      newDiv.style.fontSize = '12px';
      
      newDiv.textContent = storedEnglishTranscript[index];
      
      const segmentContent = line.querySelector('.segment');
      if (segmentContent) {
        segmentContent.appendChild(newDiv);
      }
    }
  });
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', function() {
    setTimeout(function() {
      if (openYouTubeTranscript()) {
        setTimeout(() => selectTranscriptAndStore('english'), 1000);
      }
    }, 2000);
  });
} else {
  setTimeout(function() {
    if (openYouTubeTranscript()) {
      setTimeout(() => selectTranscriptAndStore('english'), 1000);
    }
  }, 2000);
}
